# Site settings
title: Diophantic
email: carlos@diophantic.nl
description: > # this means to ignore newlines until "baseurl:"
  A blog about programming and everything related...like life, 
  liberty and the pursuit of happiness.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: Baudin999
github_username:  Baudin999

# Build settings
markdown: kramdown
